/* Generated by Phoenix Tuner X */
package frc.robot.subsystems;

import static edu.wpi.first.units.Units.*;

import edu.wpi.first.wpilibj2.command.Command;
import edu.wpi.first.wpilibj2.command.SubsystemBase;
import frc.robot.Constants;

import com.ctre.phoenix6.CANBus;
import com.ctre.phoenix6.controls.ColorFlowAnimation;
import com.ctre.phoenix6.controls.SolidColor;
import com.ctre.phoenix6.hardware.CANdle;
import com.ctre.phoenix6.signals.AnimationDirectionValue;
import com.ctre.phoenix6.signals.RGBWColor;

/**
 * Subsystem that controls an addressable LED strip using a CANdle.
 */
public class Led extends SubsystemBase {
    // private final CANBus kCANBus = new CANBus("rio");
    private final CANdle m_candle = new CANdle(Constants.LedConstants.kCandleId);

    private final ColorFlowAnimation m_slot0Animation = new ColorFlowAnimation(0, 50)
        .withSlot(0)
        .withColor(new RGBWColor(255, 254, 85, 0))
        .withDirection(AnimationDirectionValue.Forward)
        .withFrameRate(Hertz.of(25));

    private final SolidColor[] m_colors = new SolidColor[] {
        new SolidColor(0, 50).withColor(new RGBWColor(50, 45, 255, 0)), //blue
        new SolidColor(0, 50).withColor(new RGBWColor(255, 61, 20, 0)), //red
        new SolidColor(0, 50).withColor(new RGBWColor(255, 255, 255, 0)), //white
    };

    public Led() {
        // setDefaultCommand(updateLEDs());
    }

    /**
     * Updates the animations and LEDs of the CANdle.
     *
     * @return Command to run
     */
    public Command updateLEDs() {
        return run(() -> {
            for (var solidColor : m_colors) {
                m_candle.setControl(solidColor);
            }
            m_candle.setControl(m_slot0Animation);

        });
    }
}

// Copyright (c) FIRST and other WPILib contributors.
// Open Source Software; you can modify and/or share it under the terms of
// the WPILib BSD license file in the root directory of this project.

// package frc.robot.subsystems;

// import edu.wpi.first.wpilibj2.command.Commands;
// import edu.wpi.first.wpilibj2.command.SubsystemBase;
// import frc.robot.Constants;

// import static edu.wpi.first.units.Units.*;

// import com.ctre.phoenix6.CANBus;
// import com.ctre.phoenix6.configs.CANdleConfiguration;
// import com.ctre.phoenix6.controls.*;
// import com.ctre.phoenix6.hardware.CANdle;
// import com.ctre.phoenix6.signals.AnimationDirectionValue;
// import com.ctre.phoenix6.signals.RGBWColor;
// import com.ctre.phoenix6.signals.StatusLedWhenActiveValue;
// import com.ctre.phoenix6.signals.StripTypeValue;

// import edu.wpi.first.wpilibj.smartdashboard.SendableChooser;
// import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;
// import edu.wpi.first.wpilibj.util.Color;

// import edu.wpi.first.wpilibj2.command.Command;
// import edu.wpi.first.wpilibj2.command.Commands;


// public class Led extends SubsystemBase {
//   /** Creates a new Led. */
//   /* color can be constructed from RGBW, a WPILib Color/Color8Bit, HSV, or hex */
//   private static final RGBWColor kGreen = new RGBWColor(0, 217, 0, 0);
//   private static final RGBWColor kWhite = new RGBWColor(Color.kWhite).scaleBrightness(0.5);
//   private static final RGBWColor kViolet = RGBWColor.fromHSV(Degrees.of(270), 0.9, 0.8);
//   private static final RGBWColor kRed = RGBWColor.fromHex("#D9000000").orElseThrow();

//   /*
//     * Start and end index for LED animations.
//     * 0-7 are onboard, 8-399 are an external strip.
//     * CANdle supports 8 animation slots (0-7).
//     */
//   private static final int kSlot0StartIdx = 8;
//   private static final int kSlot0EndIdx = 37;

//   private static final int kSlot1StartIdx = 38;
//   private static final int kSlot1EndIdx = 67;

//   private final CANdle m_candle = new CANdle(Constants.LedConstants.kCandleId, CANBus.roboRIO());

//   public enum AnimationType {
//     None,
//     ColorFlow,
//     Fire,
//     Larson,
//     Rainbow,
//     RgbFade,
//     SingleFade,
//     Strobe,
//     Twinkle,
//     TwinkleOff,
//   }

//   public AnimationType m_anim0State = AnimationType.None;
//   public AnimationType m_anim1State = AnimationType.None;

//   private final SendableChooser<AnimationType> m_anim0Chooser = new SendableChooser<AnimationType>();
//   private final SendableChooser<AnimationType> m_anim1Chooser = new SendableChooser<AnimationType>();

//   public Led() {
//     /* Configure CANdle */
//     var cfg = new CANdleConfiguration();
//     /* set the LED strip type and brightness */
//     cfg.LED.StripType = StripTypeValue.RGBW;
//     cfg.LED.BrightnessScalar = 0.5;
//     /* disable status LED when being controlled */
//     cfg.CANdleFeatures.StatusLedWhenActive = StatusLedWhenActiveValue.Disabled;

//     m_candle.getConfigurator().apply(cfg);

//     /* clear all previous animations */
//     for (int i = 0; i < 8; ++i) {
//         m_candle.setControl(new EmptyAnimation(i));
//     }
//     /* set the onboard LEDs to a solid color */
//     m_candle.setControl(new SolidColor(0, 3).withColor(kGreen));
//     m_candle.setControl(new SolidColor(4, 7).withColor(kWhite));

//     /* add animations to chooser for slot 0 */
//     m_anim0Chooser.setDefaultOption("Color Flow", AnimationType.ColorFlow);
//     m_anim0Chooser.addOption("Rainbow", AnimationType.Rainbow);
//     m_anim0Chooser.addOption("Twinkle", AnimationType.Twinkle);
//     m_anim0Chooser.addOption("Twinkle Off", AnimationType.TwinkleOff);
//     m_anim0Chooser.addOption("Fire", AnimationType.Fire);

//     /* add animations to chooser for slot 1 */
//     m_anim1Chooser.setDefaultOption("Larson", AnimationType.Larson);
//     m_anim1Chooser.addOption("RGB Fade", AnimationType.RgbFade);
//     m_anim1Chooser.addOption("Single Fade", AnimationType.SingleFade);
//     m_anim1Chooser.addOption("Strobe", AnimationType.Strobe);
//     m_anim1Chooser.addOption("Fire", AnimationType.Fire);

//     SmartDashboard.putData("Animation 0", m_anim0Chooser);
//     SmartDashboard.putData("Animation 1", m_anim1Chooser);
//   }

// @Override
// public void periodic() {
// 	// This method will be called once per scheduler run
// 	/* if the selection for slot 0 changes, change animations */
// 	final var anim0Selection = m_anim0Chooser.getSelected();
// 	if (m_anim0State != anim0Selection) {
// 		m_anim0State = anim0Selection;

// 	switch (m_anim0State) {
// 		case ColorFlow:
// 			m_candle.setControl(
// 							new ColorFlowAnimation(kSlot0StartIdx, kSlot0EndIdx).withSlot(0)
// 											.withColor(kViolet)
// 			);
// 			break;
// 		case Rainbow:
// 			m_candle.setControl(
// 							new RainbowAnimation(kSlot0StartIdx, kSlot0EndIdx).withSlot(0)
// 			);
// 			break;
// 		case Twinkle:
// 			m_candle.setControl(
// 							new TwinkleAnimation(kSlot0StartIdx, kSlot0EndIdx).withSlot(0)
// 											.withColor(kViolet)
// 			);
// 			break;
// 		case TwinkleOff:
// 			m_candle.setControl(
// 							new TwinkleOffAnimation(kSlot0StartIdx, kSlot0EndIdx).withSlot(0)
// 											.withColor(kViolet)
// 			);
// 			break;
// 		case Fire:
// 			m_candle.setControl(
// 							new FireAnimation(kSlot0StartIdx, kSlot0EndIdx).withSlot(0)
// 			);
// 			break;
//     }
//   }}
  

//   public Command newFunsies()
//   {
//     return Commands.runOnce(() -> thing());
//   }

//   public void thing()
//   {
//     m_candle.setControl(
// 							new RainbowAnimation(kSlot0StartIdx, kSlot0EndIdx).withSlot(0));
//   }
// }

// package frc.robot.subsystems;

// import com.ctre.phoenix6.CANBus;
// import com.ctre.phoenix6.configs.CANdleConfiguration;
// import com.ctre.phoenix6.hardware.CANdle;

// import com.ctre.phoenix6.controls.*;
// import com.ctre.phoenix6.signals.AnimationDirectionValue;
// import com.ctre.phoenix6.signals.Enable5VRailValue;
// import com.ctre.phoenix6.signals.RGBWColor;
// import com.ctre.phoenix6.signals.StatusLedWhenActiveValue;
// import com.ctre.phoenix6.signals.StripTypeValue;

// import edu.wpi.first.hal.SimDevice.Direction;
// import edu.wpi.first.wpilibj2.command.Command;
// import edu.wpi.first.wpilibj2.command.SubsystemBase;
// import frc.robot.Constants;

// public class Led extends SubsystemBase {
//     private static final CANdle candle = new CANdle(15);

//     // Team colors
//     public static final Color blue = new Color(0, 0, 255);
//     public static final Color yellow = new Color(255, 255, 0);

//     // Indicator colors
//     public static final Color white = new Color(255, 230, 220);
//     public static final Color red = new Color(255, 0, 0);

//     public Led() {
//         CANdleConfiguration candleConfiguration = new CANdleConfiguration();

//         candleConfiguration.FutureProofConfigs = true;
//         candleConfiguration.CANdleFeatures.Enable5VRail = Enable5VRailValue.Enabled;
//         candleConfiguration.CANdleFeatures.StatusLedWhenActive = StatusLedWhenActiveValue.Enabled;
//         candleConfiguration.LED.StripType = StripTypeValue.RGBW;
//         candleConfiguration.LED.BrightnessScalar = 0.5;
//         candleConfiguration.CANdleFeatures.StatusLedWhenActive = StatusLedWhenActiveValue.Disabled;

//         candle.getConfigurator().apply(candleConfiguration);

//         candleConfiguration.CANdleFeatures.Enable5VRail = Enable5VRailValue.Enabled;
//         candleConfiguration.CANdleFeatures.StatusLedWhenActive = StatusLedWhenActiveValue.Enabled;
//         candleConfiguration.LED.StripType = StripTypeValue.RGBW;
//         candleConfiguration.LED.BrightnessScalar = 0.5;
//         candleConfiguration.CANdleFeatures.StatusLedWhenActive = StatusLedWhenActiveValue.Disabled;

//         setDefaultCommand(defaultCommand());
//     }

//     // public void setBrightness(double percent) {
//     //     candle.configBrightnessScalar(percent, 100);
//     // }

//     public Command defaultCommand() {
//         return runOnce(() -> {
//             // LEDSegment.BatteryIndicator.fullClear();
//             // LEDSegment.PressureIndicator.fullClear();
//             // LEDSegment.MastEncoderIndicator.fullClear();
//             // LEDSegment.BoomEncoderIndicator.fullClear();
//             // LEDSegment.WristEncoderIndicator.fullClear();

//             // LEDSegment.MainStrip.setColor(blue);
//         });
//     }

//     // public Command clearSegmentCommand(LEDSegment segment) {
//     //     return runOnce(() -> {
//     //         segment.clearAnimation();
//     //         segment.disableLEDs();
//     //     });
//     }

//         public void setColor(Color color) {
//             candle.setColor(color.red, color.green, color.blue, 0, 0, 0);
//         }

//         // private void setAnimation(Animation animation) {
//         //     candle.animate(animation, animationSlot);
//         // }

//         // public void fullClear() {
//         //     clearAnimation();
//         //     disableLEDs();
//         // }

//         // public void clearAnimation() {
//         //     candle.clearAnimation(animationSlot);
//         // }

//         public void disableLEDs() {
//             candle.setLEDs(white);
//         }

//         public void setFlowAnimation(Color color, double speed) {
//             candle.setControl(new ColorFlowAnimation(
//                     color.red, color.green, color.blue, 0, speed, segmentSize, Direction.values(eee), startIndex));
//         }

//         // public void setFadeAnimation(Color color, double speed) {
//         //     setAnimation(
//         //             new SingleFadeAnimation(color.red, color.green, color.blue, 0, speed, segmentSize, startIndex));
//         // }

//         // public void setBandAnimation(Color color, double speed) {
//         //     setAnimation(new LarsonAnimation(
//         //             color.red, color.green, color.blue, 0, speed, segmentSize, BounceMode.Front, 3, startIndex));
//         // }

//         // public void setStrobeAnimation(Color color, double speed) {
//         //     setAnimation(new StrobeAnimation(color.red, color.green, color.blue, 0, speed, segmentSize, startIndex));
//         // }

//         // public void setRainbowAnimation(double speed) {
//         //     setAnimation(new RainbowAnimation(1, speed, segmentSize, false, startIndex));
//         // }
//     }

//     public static class Color {
//         public int red;
//         public int green;
//         public int blue;

//         public Color(int red, int green, int blue) {
//             this.red = red;
//             this.green = green;
//             this.blue = blue;
//         }

//         /**
//          * Highly imperfect way of dimming the LEDs. It does not maintain color or
//          * accurately adjust perceived brightness.
//          *
//          * @param dimFactor
//          * @return The dimmed color
//          */
//         // public Color dim(double dimFactor) {
//         //     int newRed = (int) (MathUtils.ensureRange(red * dimFactor, 0, 200));
//         //     int newGreen = (int) (MathUtils.ensureRange(green * dimFactor, 0, 200));
//         //     int newBlue = (int) (MathUtils.ensureRange(blue * dimFactor, 0, 200));

//         //     return new Color(newRed, newGreen, newBlue);
//         // }
//     }
// }